#define _GNU_SOURCE

#include <errno.h>
#include <error.h>
#include <stdio.h>
#include <stdio.h>

// void error_at_line (int status, int errnum, const char *fname, unsigned int lineno, const char *format, …)

// The [error_at_line] function is very similar to the error function.
// The only differences are the additional parameters [fname] and [lineno]
// The handling of the other parameters is identical to that of error except
// that between the program name and the string generated by the format string
// text is inserted.

// Directly following the program name a colon, followed by the file name pointed
// to by fname, another colon, and the value of lineno is printed.

// This additional output of course is meant to be used to locate an error in an
// input file (like a programming language source code file etc.)

// If the global variable [error_one_per_line] is set to a non-zero value
// error_at_line will avoid printing consecutive messages for the same file
// and line. Repetition which are not directly following each other are not
// caught.

// As memtioned above, the [error] and [error_at_line] functions can be
// customized by defining a variable named [error_print_progname]

/*

$ ./hello_error_at_line 

filename: hello_error_at_line
file:1: error message

filename: hello_error_at_line
error_at_line_usage:3: error message

*/

void custom_error_print_progname(void)
{
	printf("\nfilename: %s\n", program_invocation_short_name);
}

void error_at_line_usage(void)
{
	error_print_progname = custom_error_print_progname;
	// error_at_line(0, 0, NULL, 0, "error message");
	error_at_line(0, 0, "file", 1, "error message");
	error_at_line(0, 0, "error_at_line_usage", 3, "error message");
}

int main(void)
{
	error_at_line_usage();
	return 0;
}

// https://www.gnu.org/software/libc/manual/html_mono/libc.html#Error-Reporting
// https://sourceware.org/bugzilla/show_bug.cgi?id=2997
