# Makefile for LINUX (UBUNTU / 16.04) Testing  ..
#
#
#
# Nixawk
#
# This makefile can build 1 executable. The executable
# can be injected a backdoor feature from backdoor.c
#

CC = gcc

hello:
	$(CC) -o hello hello.c backdoor.c